var annotated_dup =
[
    [ "buf", "structbuf.html", "structbuf" ],
    [ "condvar", "structcondvar.html", "structcondvar" ],
    [ "context", "structcontext.html", "structcontext" ],
    [ "dinode", "structdinode.html", "structdinode" ],
    [ "dirent", "structdirent.html", "structdirent" ],
    [ "file", "structfile.html", "structfile" ],
    [ "FSManager", "structFSManager.html", "structFSManager" ],
    [ "inode", "structinode.html", "structinode" ],
    [ "manager", "structmanager.html", "structmanager" ],
    [ "mutex", "structmutex.html", "structmutex" ],
    [ "pipe", "structpipe.html", "structpipe" ],
    [ "pipe_context", "structpipe__context.html", "structpipe__context" ],
    [ "proc", "structproc.html", "structproc" ],
    [ "queue", "structqueue.html", "structqueue" ],
    [ "semaphore", "structsemaphore.html", "structsemaphore" ],
    [ "superblock", "structsuperblock.html", "structsuperblock" ],
    [ "syscall_context", "structsyscall__context.html", "structsyscall__context" ],
    [ "thread", "structthread.html", "structthread" ],
    [ "TimeVal", "structTimeVal.html", "structTimeVal" ],
    [ "trap_handler_context", "structtrap__handler__context.html", "structtrap__handler__context" ],
    [ "trapframe", "structtrapframe.html", "structtrapframe" ],
    [ "virtio_blk_req", "structvirtio__blk__req.html", "structvirtio__blk__req" ],
    [ "virtio_context", "structvirtio__context.html", "structvirtio__context" ],
    [ "virtq_avail", "structvirtq__avail.html", "structvirtq__avail" ],
    [ "virtq_desc", "structvirtq__desc.html", "structvirtq__desc" ],
    [ "virtq_used", "structvirtq__used.html", "structvirtq__used" ],
    [ "virtq_used_elem", "structvirtq__used__elem.html", "structvirtq__used__elem" ]
];